### ISSUE TITLE
UI improvements (back button, settings menu etc)

### ISSUE THREAD

**Issue by maxogden** [maxogden/screencat#11]
The UI is pretty barebones. If anyone wants to PR any UI improvements I would happily merge. Just ask before spending time integrating any large frameworks/dependencies

**Comment by vrunoa** [comment]
What do you think on using [fontawesome](http://fontawesome.io/icons/) for the app icons(back button,...) ? I could add this.

**Comment by maxogden** [comment]
@vrunoa fontawesome looks cool, but our UI is so minimal right now I kind of think we should wait until it evolves a little more before adding them

**Comment by vrunoa** [comment]
np @maxogden. let me know when you have a new design, I can help you build the ui.

**Comment by jsimplicio** [comment]
Could I use Sass?
