### ISSUE TITLE
I don't get the screen code to share

### ISSUE THREAD

**Issue by vrunoa** [maxogden/screencat#18]
I clone the repo and run ```npm run app``` and never get the screen code to share. 

I don't know if has anything to do with it, but in the console I get this error:
```node
[40713:0328/162940:INFO:CONSOLE(118)] "Uncaught Error: Module did not self-register.", source: ATOM_SHELL_ASAR.js (118)
```
I'm on Yosemite(v10.10.2).

**Comment by maxogden** [comment]
@vrunoa hi, you need to follow the instructions here https://github.com/maxogden/screencat#developing, specifically the paragraph at the bottom

**Comment by vrunoa** [comment]
Sorry for not reading the last paragraph. Not it's working great!

**Comment by HParker** [comment]
@maxogden it is possible I am doing something very silly, but after running export `ATOM_NODE_VERSION=0.22.1 && apm install .`, when I try to get the screen share code I am getting

```
$ npm start

> screencat@2.0.0 start /Users/adam/code/screencat
> electron app.js

ready
[66386:1004/221349:INFO:CONSOLE(338)] "Uncaught Error: Cannot find module 'robotjs'", source: module.js (338)
```

Is it possible the atom node version in the readme is not up to date?
