### ISSUE TITLE
mozInnerScreenX

### ISSUE THREAD

**Issue by zz85** [maxogden/ScreenCat#2]
I was looking at the mdn's documentation and realized that [mozInnerScreenX](https://developer.mozilla.org/en-US/docs/Web/API/Window.mozInnerScreenX) was what we were looking for the other night.

unfortunately, doesn't look implemented [by other vendors](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/xOtoSLgaiPY) right now.

<a href="http://stackoverflow.com/questions/8078770/how-do-you-get-a-browsers-document-body-coordinates-with-respect-to-the-screen"><img src="http://i.stack.imgur.com/o2Rpa.jpg" /></a>

So i guess mouse events' hack probably still work well. cc. @timoxley

**Comment by maxogden** [comment]
i rewrote most of this to be an atom-shell app, and now there are nice atom-shell apis we can use for this instead!

**Comment by zz85** [comment]
@maxogden just checked back on this... looks like this new approach is exciting! will try out and see :+1:
