### ISSUE TITLE
double-click, scrolling etc (overall better mouse stuff)

### ISSUE THREAD

**Issue by maxogden** [maxogden/screencat#23]
right now we only support single clicking. improving this is dependent upon what we can get into https://github.com/octalmage/robotjs. My current fork is here https://github.com/maxogden/robotjs/tree/keyupdown. I intended to PR it at some point

**Comment by octalmage** [comment]
I started work on this for octalmage/RobotJS#24, but it's proving to be harder than I thought. It looks like there's a separate event for double clicks. I'll update this if I make any progress.
