### ISSUE TITLE
The Lobby is down

### ISSUE THREAD

**Issue by techwritescode** [maxogden/screencat#51]
I cannot connect to the lobby
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
 EventSource cannot load http://catlobby.maxogden.com/v1/salem-gracie-zoe/pings. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://maxogden.github.io' is therefore not allowed access. The response had HTTP status code 504.

**Comment by max-mapper** [comment]
Ah dang, thanks for reporting. I just restarted the process and it seems to
be running now.

Longer term I need to migrate this to use http://npmjs.org/signalhub which
is designed to handle failover more easily than cat lobby.

**Comment by techwritescode** [comment]
### 504 Gateway Time-out

nginx

**Comment by techwritescode** [comment]
and btw npm i robotjs@latest fixes some problems
