### ISSUE TITLE
Robotjs failed to load in MacOSX

### ISSUE THREAD

**Issue by humanely** [maxogden/screencat#57]
Hi,

This gives error to load robotjs in mac. Has anyone faced this issue?

[Error: ./robot.js failed to load]
[Error: Module version mismatch. Expected 47, got 48.]

**Comment by msakrejda** [comment]
I've seen this in other projects, generally when switching node versions without rebuilding native modules (but sometimes in other situations). Running `rm -rf node_modules && npm install` has always fixed it for me.

**Comment by humanely** [comment]
Tried that. But problem still exists. Also, as mentioned in Robotjs [here](https://github.com/octalmage/robotjs/wiki/Electron) but no help.

**Comment by humanely** [comment]
After some trials and cache cleanups, I am getting:

[Error: ./robot.js failed to load]
[Error: Module version mismatch. Expected 47, got 51.]

**Comment by mafintosh** [comment]
you need to build it against electron after installing, npm run rebuild, https://github.com/maxogden/screencat/blob/master/package.json#L11

**Comment by humanely** [comment]
At last! This solved my issue. http://electron.atom.io/docs/tutorial/using-native-node-modules/
./node_modules/.bin/electron-rebuild
