### ISSUE TITLE
Where is remote-bundle.js & server 

### ISSUE THREAD

**Issue by humanely** [maxogden/screencat#58]
Hi,

Two questions(may be novice level):

- Where is remote-bundle.js [As here](https://github.com/maxogden/screencat/blob/master/remote.html#L58)  ? How do you run on [github.io](http://maxogden.github.io/screencat/remote.html)? I think xhr are not allowed on github?

- How are the services built, like catlobby?  
`var server = 'http://catlobby.maxogden.com'
  // var server = 'http://localhost:5005'
  var remoteConfigUrl = 'https://instant.io/rtcConfig'`

**Comment by talarari** [comment]
you need to bundle it yourself, look here:
https://github.com/maxogden/screencat/issues/59
