### ISSUE TITLE
ENOTFOUND catlobby.maxodgen.com

### ISSUE THREAD

**Issue by mcmunder** [maxogden/screencat#60]
Just wanted to test screencat and got the error show in the attached screenshot. Seems like the cat-lobby server is down?! Any advice? Thanks in advance!

![screenshot 2016-12-01 11 12 01](https://cloud.githubusercontent.com/assets/5681686/20790107/3e702714-b7b7-11e6-8895-f877446082a8.png)

**Comment by LaurentFough** [comment]
Ditto here.
Sad cat face.

**Comment by 748890753yiyi** [comment]
Ditto here

**Comment by filipesperandio** [comment]
Seems like this is dead for a while

**Comment by mcmunder** [comment]
Closing this cause its really outdated.
