### ISSUE TITLE
What's is remoteConfigUrl?

### ISSUE THREAD

**Issue by roy2651** [maxogden/screencat#67]
hello,friend
   I get function getRemoteConfig() ,is this get remote webrtc config(ice/stun/turn) ,how I modify var remoteConfigUrl to my iceserver 
  I  use coturn in my server , and  how to use my coturn server
 Thank u and God bless u

**Comment by roy2651** [comment]
I find this remoteConfigUrl is a http ask and get a json like {"iceserver":["urls" :{}]},
you can get the result by var remoteConfigUrl = 'https://instant.io/_rtcConfig',
you can get some info ,so I write an api get result like remoteConfigUrl. 
If u get this, u can get everywhere whatever innernet or internet.

**Comment by XI803-ManikMahendru** [comment]
It is not resolved
